#!/bin/sh
# This script prepares an Alpine Linux cloud image for OVHcloud baremetal servers.
set -eu

# Place the post-install script that the deployer runs, chrooted, on the target.
mkdir -p /root/.ovh
mv /tmp/make_image_bootable.sh /root/.ovh/make_image_bootable.sh
chmod +x /root/.ovh/make_image_bootable.sh

### Phase 1: System upgrade and packages ###

apk update
apk upgrade --no-cache

# Bare-metal tooling plus the tools make_image_bootable.sh needs at deploy time:
# - bash + GNU grep/sed: make_image_bootable.sh uses bash and grep -P;
# - grub, grub-bios, grub-efi: legacy and UEFI bootloader install;
# - findmnt, lsblk: boot-disk detection in make_image_bootable.sh;
# - linux-firmware-intel: ice firmware for Intel E810 NICs on some servers.
apk add --no-cache \
    bash \
    grep \
    sed \
    grub \
    grub-bios \
    grub-efi \
    mdadm \
    lvm2 \
    btrfs-progs \
    dosfstools \
    xfsprogs \
    linux-firmware-intel \
    intel-ucode \
    amd-ucode \
    findmnt \
    lsblk

### Phase 2: Network and GRUB configuration ###

# Remove the cloud image's static network configuration so cloud-init manages
# networking at first boot.
rm -f /etc/network/interfaces

# GRUB defaults for bare-metal (console params are added at deploy time by
# make_image_bootable.sh).
cat > /etc/default/grub <<'EOF'
# This file has been generated by OVHcloud for bare-metal boot.
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="Alpine"
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX="nomodeset iommu=pt"
GRUB_GFXPAYLOAD_LINUX="text"
EOF

# Embed the modules needed to find the root device on bare-metal (disk
# controllers, RAID, LVM, filesystems, NICs for early cloud-init).
echo 'features="ata base ide scsi usb virtio nvme raid lvm ext4 xfs btrfs network"' \
    > /etc/mkinitfs/mkinitfs.conf

# The Alpine cloud image is a whole-disk filesystem with no partition table, which
# BYOL rejects ("too many partitions", from the SYSLINUX boot sector being misread
# as an MBR). It is converted into a single-partition image after the build by
# tools/wrap-single-partition.sh, so there is nothing to partition here.

### Phase 3: Cleanup ###

# machine-id is regenerated by make_image_bootable.sh during installation.
rm -f /etc/machine-id
rm -rf /var/cache/apk/*
