#!/bin/sh
# This script prepares an Alpine Linux cloud image for OVHcloud baremetal servers

set -eu

# Update the system
apk update
apk upgrade --no-cache

# Install useful packages for baremetal (RAID/LVM/filesystems/microcodes/bootloader).
# - bash is required by /root/.ovh/make_image_bootable.sh
# - grub-bios and grub-efi cover both legacy and UEFI servers (the right one is
#   selected at install time by make_image_bootable.sh)
# - linux-firmware-intel ships ice firmware for Intel E810 NICs found on some
#   baremetal servers
apk add --no-cache \
    bash \
    grub \
    grub-bios \
    grub-efi \
    mdadm \
    lvm2 \
    btrfs-progs \
    dosfstools \
    xfsprogs \
    linux-firmware-intel \
    intel-ucode \
    amd-ucode \
    parted \
    rsync \
    findmnt \
    lsblk \
    util-linux-misc

# Remove the cloud image's static network configuration so cloud-init can manage
# networking at first boot
rm -f /etc/network/interfaces

# Configure GRUB for baremetal boot (console parameters are added at install time
# by make_image_bootable.sh)
cat > /etc/default/grub <<'EOF'
# This file has been generated by OVHcloud for baremetal boot.
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="Alpine"
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX="nomodeset iommu=pt"
GRUB_GFXPAYLOAD_LINUX="text"
EOF

# Make sure the initramfs embeds the modules needed to find the root device on
# baremetal (disk controllers, RAID, LVM, filesystems, NICs for early cloud-init).
echo 'features="ata base ide scsi usb virtio nvme raid lvm ext4 xfs btrfs network"' \
    > /etc/mkinitfs/mkinitfs.conf

### Make the image single-partition (BYOL requirement) ###
# The Alpine cloud image ships an ESP and a bios_grub stub alongside the Linux
# root partition, but BYOL requires a single partition. Merge the ESP into the
# root filesystem and delete the extra partitions; the target's real ESP is
# recreated by OVHcloud partitioning and make_image_bootable.sh reinstalls GRUB
# there at deploy time. blkdiscard before parted rm releases the freed blocks in
# the qcow2 instead of leaving them allocated.
root_disk="$(lsblk -no PKNAME "$(findmnt -n -o SOURCE /)")"
efi_dev="$(findmnt -n -o SOURCE /boot/efi 2>/dev/null || true)"
if [ -n "$efi_dev" ]; then
    echo "Merging /boot/efi ($efi_dev) into the root filesystem"
    efi_partnum="$(lsblk -no PARTN "$efi_dev")"
    rsync -aSH /boot/efi/ /boot_efi.new/
    umount /boot/efi
    blkdiscard "$efi_dev"
    rsync -aSH /boot_efi.new/ /boot/efi/
    rm -rf /boot_efi.new
    parted "/dev/$root_disk" -s "rm $efi_partnum"
fi
# Remove any bios_grub stub partition (GPT type 21686148-6449-6e6f-744e-656564454649).
lsblk -nro NAME,PARTTYPE "/dev/$root_disk" | while read -r part parttype; do
    if [ "$parttype" = "21686148-6449-6e6f-744e-656564454649" ]; then
        echo "Removing bios_grub stub partition /dev/$part"
        blkdiscard "/dev/$part"
        parted "/dev/$root_disk" -s "rm $(lsblk -no PARTN "/dev/$part")"
    fi
done

# Remove machine-id, it is regenerated by make_image_bootable.sh during installation
rm -f /etc/machine-id

# Clean package cache
rm -rf /var/cache/apk/*
