#!/bin/sh
# This script prepares an Alpine Linux cloud image for OVHcloud baremetal servers.
set -eu

# Place the post-install script that the deployer runs, chrooted, on the target.
mkdir -p /root/.ovh
mv /tmp/make_image_bootable.sh /root/.ovh/make_image_bootable.sh
chmod +x /root/.ovh/make_image_bootable.sh

### Phase 1: System upgrade and packages ###

apk update
apk upgrade --no-cache

# Bare-metal tooling plus the tools make_image_bootable.sh needs at deploy time:
# - bash + GNU grep/sed: make_image_bootable.sh uses bash and grep -P;
# - grub, grub-bios, grub-efi: legacy and UEFI bootloader install;
# - parted, rsync, findmnt, lsblk, util-linux-misc (blkdiscard): partition tools
#   for the single-partition step below;
# - linux-firmware-intel: ice firmware for Intel E810 NICs on some servers.
apk add --no-cache \
    bash \
    grep \
    sed \
    grub \
    grub-bios \
    grub-efi \
    mdadm \
    lvm2 \
    btrfs-progs \
    dosfstools \
    xfsprogs \
    linux-firmware-intel \
    intel-ucode \
    amd-ucode \
    parted \
    rsync \
    findmnt \
    lsblk \
    util-linux-misc

### Phase 2: Network and GRUB configuration ###

# Remove the cloud image's static network configuration so cloud-init manages
# networking at first boot.
rm -f /etc/network/interfaces

# GRUB defaults for bare-metal (console params are added at deploy time by
# make_image_bootable.sh).
cat > /etc/default/grub <<'EOF'
# This file has been generated by OVHcloud for bare-metal boot.
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="Alpine"
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX="nomodeset iommu=pt"
GRUB_GFXPAYLOAD_LINUX="text"
EOF

# Embed the modules needed to find the root device on bare-metal (disk
# controllers, RAID, LVM, filesystems, NICs for early cloud-init).
echo 'features="ata base ide scsi usb virtio nvme raid lvm ext4 xfs btrfs network"' \
    > /etc/mkinitfs/mkinitfs.conf

### Phase 3: Single-partition image (BYOL requires exactly one partition) ###
# The Alpine cloud image ships an ESP (and/or a bios_grub stub) alongside the
# Linux root. Remove every partition except root so the image is single-partition
# — the Alpine metal image's ESP is not mounted at /boot/efi under BIOS boot, so
# match by "not the root partition" rather than by mountpoint/type. Any mounted
# extra partition's content is copied into the root filesystem first; the target
# gets a fresh ESP from OVHcloud partitioning and make_image_bootable.sh installs
# GRUB there at deploy time. blkdiscard before parted rm releases the freed
# blocks in the qcow2. Trailing digits of the device name are the partition
# number (the lsblk PARTN column is not available on older util-linux).
root_src="$(findmnt -n -o SOURCE /)"
root_disk="$(lsblk -no PKNAME "$root_src")"
lsblk -nro NAME "/dev/$root_disk" | while read -r name; do
    dev="/dev/$name"
    [ "$name" = "$root_disk" ] && continue   # the disk itself
    [ "$dev" = "$root_src" ] && continue      # the root partition
    mnt="$(findmnt -n -o TARGET "$dev" 2>/dev/null || true)"
    if [ -n "$mnt" ]; then
        echo "Merging $mnt ($dev) into the root filesystem"
        rsync -aSH "$mnt/" /part_merge/
        umount "$dev"
        rsync -aSH /part_merge/ "$mnt/"
        rm -rf /part_merge
    fi
    echo "Removing partition $dev"
    blkdiscard "$dev" || true
    parted "/dev/$root_disk" -s "rm ${name##*[!0-9]}"
done

### Phase 4: Cleanup ###

# machine-id is regenerated by make_image_bootable.sh during installation.
rm -f /etc/machine-id
rm -rf /var/cache/apk/*
