#!/bin/bash
# This script prepares an Arch Linux cloud image for OVHcloud baremetal servers.
set -euo pipefail

# Place the post-install script that the deployer runs, chrooted, on the target.
mkdir -p /root/.ovh
mv /tmp/make_image_bootable.sh /root/.ovh/make_image_bootable.sh
chmod +x /root/.ovh/make_image_bootable.sh

### Phase 1: System upgrade and packages ###

pacman -Syu --noconfirm

# Bare-metal tooling: RAID/LVM/filesystems, microcodes, early NIC firmware, plus
# the partition tools used by the single-partition step below.
# linux-firmware-intel carries ice.pkg for Intel E810 NICs; mkinitcpio-nfs-utils
# loads networking drivers early so cloud-init works on first boot.
pacman -S --noconfirm --needed \
    mdadm \
    lvm2 \
    btrfs-progs \
    dosfstools \
    xfsprogs \
    linux-firmware-intel \
    intel-ucode \
    amd-ucode \
    mkinitcpio-nfs-utils \
    parted \
    rsync

### Phase 2: Network and GRUB configuration ###

# Remove the cloud image's static network configuration so cloud-init manages
# networking at first boot.
rm -f /etc/systemd/network/*.network

# nomodeset: KVM display on some boards. Boot in text mode for compatibility.
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=""/' /etc/default/grub
sed -i 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="nomodeset iommu=pt"/' /etc/default/grub
sed -i 's/GRUB_GFXPAYLOAD_LINUX=.*/GRUB_GFXPAYLOAD_LINUX="text"/' /etc/default/grub

# Initramfs hooks: microcode early, mdadm/LVM and networking for bare-metal.
sed -i 's/^HOOKS=.*/HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap sd-vconsole block mdadm_udev lvm2 net filesystems fsck)/' /etc/mkinitcpio.conf

### Phase 3: Single-partition image (BYOL requires exactly one partition) ###
# Merge the ESP into the root filesystem and delete the extra partitions; the
# target's real ESP is recreated by OVHcloud partitioning and
# make_image_bootable.sh reinstalls GRUB there at deploy time. blkdiscard before
# parted rm so the freed blocks are actually released in the qcow2.
root_disk="$(lsblk -no PKNAME "$(findmnt -n -o SOURCE /)")"
efi_dev="$(findmnt -n -o SOURCE /boot/efi 2>/dev/null || true)"
if [ -n "$efi_dev" ]; then
    echo "Merging /boot/efi ($efi_dev) into the root filesystem"
    # Trailing digits of the device name are the partition number (PARTN is not
    # available on older util-linux).
    efi_partnum="${efi_dev##*[!0-9]}"
    rsync -aSH /boot/efi/ /boot_efi.new/
    umount /boot/efi
    blkdiscard "$efi_dev" || true
    rsync -aSH /boot_efi.new/ /boot/efi/
    rm -rf /boot_efi.new
    parted "/dev/$root_disk" -s "rm $efi_partnum"
fi
# Remove any bios_grub stub partition (GPT type 21686148-6449-6e6f-744e-656564454649).
lsblk -nro NAME,PARTTYPE "/dev/$root_disk" | while read -r part parttype; do
    if [ "$parttype" = "21686148-6449-6e6f-744e-656564454649" ]; then
        echo "Removing bios_grub stub partition /dev/$part"
        blkdiscard "/dev/$part" || true
        parted "/dev/$root_disk" -s "rm ${part##*[!0-9]}"
    fi
done

### Phase 4: Cleanup ###

# machine-id is regenerated by make_image_bootable.sh during installation.
rm -f /etc/machine-id
pacman -Scc --noconfirm
